### ISSUE TITLE
Carp ERROR on CollectWgsMetrics

### ISSUE THREAD

**Issue by johnmous** [biopet/biopet#201]
`CollectWgsMetrics` fails because the input file gets removed. Input file gets removed by `MarkDuplicates` when it finishes because it is marked as intermediate.

Input of `MarkDuplicates` is `.../samples/sampleName-input/lib_Library0/sampleName-input-Library0.bam`, while input of  `CollectWgsMetrics` is a link on the aforementioned file. Setting both tools to work on the exact same file might resolve the issue

**Comment by ffinfo** [comment]
Fixed by #202
